#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-stringtemplate
Version  : 3.2.1
Release  : 1
URL      : https://github.com/antlr/website-st4/raw/gh-pages/download/stringtemplate-3.2.1.tar.gz
Source0  : https://github.com/antlr/website-st4/raw/gh-pages/download/stringtemplate-3.2.1.tar.gz
Source1  : https://repo1.maven.org/maven2/org/antlr/stringtemplate/3.2.1/stringtemplate-3.2.1.jar
Source2  : https://repo1.maven.org/maven2/org/antlr/stringtemplate/3.2.1/stringtemplate-3.2.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: mvn-stringtemplate-data = %{version}-%{release}

%description
StringTemplate 3.2.1
September 22, 2009
Terence Parr, parrt at cs usfca edu
ANTLR project lead and supreme dictator for life
University of San Francisco

%package data
Summary: data components for the mvn-stringtemplate package.
Group: Data

%description data
data components for the mvn-stringtemplate package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/antlr/stringtemplate/3.2.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/antlr/stringtemplate/3.2.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/antlr/stringtemplate/3.2.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/antlr/stringtemplate/3.2.1


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/antlr/stringtemplate/3.2.1/stringtemplate-3.2.1.jar
/usr/share/java/.m2/repository/org/antlr/stringtemplate/3.2.1/stringtemplate-3.2.1.pom
